// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBQhVPUBa6JCuN13p3aLIg3SrM5PclFlU',
    appId: '1:124248554442:web:758133052ba6b790d72d33',
    messagingSenderId: '124248554442',
    projectId: 'connectinno-firebase-task',
    authDomain: 'connectinno-firebase-task.firebaseapp.com',
    storageBucket: 'connectinno-firebase-task.firebasestorage.app',
    measurementId: 'G-S69NFKSF1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKlI5B-7SaQsEUg0YOIxEogj9hCeaobFA',
    appId: '1:124248554442:android:ecbcac8326558647d72d33',
    messagingSenderId: '124248554442',
    projectId: 'connectinno-firebase-task',
    storageBucket: 'connectinno-firebase-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0IqOUqN48neKZZdUkhVLeJLhwoeR8GP0',
    appId: '1:124248554442:ios:a0ac557033b2eef7d72d33',
    messagingSenderId: '124248554442',
    projectId: 'connectinno-firebase-task',
    storageBucket: 'connectinno-firebase-task.firebasestorage.app',
    iosBundleId: 'com.example.connectinnoTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0IqOUqN48neKZZdUkhVLeJLhwoeR8GP0',
    appId: '1:124248554442:ios:a0ac557033b2eef7d72d33',
    messagingSenderId: '124248554442',
    projectId: 'connectinno-firebase-task',
    storageBucket: 'connectinno-firebase-task.firebasestorage.app',
    iosBundleId: 'com.example.connectinnoTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBQhVPUBa6JCuN13p3aLIg3SrM5PclFlU',
    appId: '1:124248554442:web:2b55c6e40f2dbf22d72d33',
    messagingSenderId: '124248554442',
    projectId: 'connectinno-firebase-task',
    authDomain: 'connectinno-firebase-task.firebaseapp.com',
    storageBucket: 'connectinno-firebase-task.firebasestorage.app',
    measurementId: 'G-FRJ7RFM18V',
  );
}
